on: 
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    - name: 📂 Move Files
      run: |
        mv -v ./dist/* ./
        rmdir dist
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ''
        username: 'sysuser_1'
        password: ${{ secrets.password }}
        protocol: ftps
        server-dir: /httpdocs/
        exclude: |
          .git*/**
          .gitignore
          node_modules/**
          src/**
          README.md
          package.json
          package-lock.json
          LICENSE
